### ISSUE TITLE
FirebaseApp: Firebase API initialization failure.

### ISSUE THREAD

**Issue by divya2392** [divya2392/UdacityFireBase#1]
04-05 16:54:24.340 26881-26881/com.google.firebase.udacity.friendlychat E/FirebaseApp: Firebase API initialization failure.
                                                                                       java.lang.reflect.InvocationTargetException
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5174)
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4769)
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4709)
                                                                                           at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                        Caused by: java.lang.NoSuchMethodError: No static method zzy(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/com.google.firebase.udacity.friendlychat-2/split_lib_dependencies_apk.apk:classes25.dex)
                                                                                           at com.google.android.gms.measurement.internal.zzx.zzdt(Unknown Source)
                                                                                           at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                                                           at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                                                           at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:5174) 
                                                                                           at android.app.ActivityThread.installContentProviders(ActivityThread.java:4769) 
                                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4709) 
                                                                                           at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by divya2392** [comment]
Issue Solved! after changing dependency
 compile 'com.google.firebase:firebase-database:9.6.0'
    compile 'com.google.firebase:firebase-auth:9.6.0'

    compile 'com.firebaseui:firebase-ui-auth:1.2.0'

to

 compile 'com.google.firebase:firebase-database:10.2.0'
    compile 'com.google.firebase:firebase-auth:10.2.0'

    compile 'com.firebaseui:firebase-ui-auth:1.2.0'
